export const MOTIVATIONAL_QUOTES = [
  "You are not just my wife — you are my greatest motivation. Now go conquer today, Tanha. 🌸💪",
  "The most beautiful thing I've ever seen is you deciding to show up for yourself every single day. Keep going. 💖",
  "Soft heart, strong mind, unstoppable soul — that's my Tanha. Today is yours. ✨",
  "I fell in love with your strength before anything else. Show the world what I already know. 🔥❤️",
  "You don't need to be perfect, lokki amar. You just need to try — and you always do. That's why I love you. 💕",
  "Every small step you take today is a giant leap in my eyes. I see you. I love you. Now go. 💌",
  "The girl who completes her tasks is the same girl who stole my heart completely. Be her today. 🥰",
  "Hard days are just proof that you are doing real things. And real things matter. You matter. I love you, Tanha. 💖",
  "My favorite version of you is the one who tries — and that's every version of you. Go be incredible today. 🌟",
  "You carry so much and still show up every day. That's not ordinary, Tanha. That's extraordinary. I love you endlessly. 🌙💕",
  "Today will be better because you're in it. The world doesn't know it yet, but I do. Go show them. 💪🌸",
  "Some people have superpowers. Mine is watching you grow every single day. You're my hero, lokki. ❤️",
  "Rest when you need to. Cry when you must. But always remember — I'm cheering for you from every corner of this universe. 🥺💖",
  "You are the reason I believe in beautiful things. Now go do beautiful things today, Tanha. 🌺",
  "Dekho, another day — another chance to be the Tanha I am endlessly proud of. Make it count, amar lokki. 🔥💕"
];

export const KEYWORD_EMOJI_MAP: Record<string, string> = {
  "gym": "💪",
  "workout": "💪",
  "exercise": "💪",
  "study": "📚",
  "read": "📚",
  "book": "📚",
  "sleep": "😴",
  "rest": "😴",
  "nap": "😴",
  "food": "🍽️",
  "eat": "🍽️",
  "lunch": "🍽️",
  "dinner": "🍽️",
  "cook": "🍽️",
  "call": "📞",
  "phone": "📞",
  "mom": "📞",
  "dad": "📞",
  "walk": "🏃",
  "run": "🏃",
  "jog": "🏃",
  "pray": "🧘",
  "meditation": "🧘",
  "mindful": "🧘",
  "code": "💻",
  "work": "💻",
  "laptop": "💻",
  "water": "💧",
  "drink": "💧",
  "medicine": "💊",
  "pill": "💊",
  "vitamin": "💊",
  "pet": "🐾",
  "dog": "🐾",
  "cat": "🐾",
  "feed": "🐾",
  "shop": "🛒",
  "buy": "🛒",
  "market": "🛒",
  "clean": "🧹",
  "wash": "🧹",
  "laundry": "🧹",
  "music": "🎵",
  "guitar": "🎵",
  "piano": "🎵",
  "draw": "🎨",
  "art": "🎨",
  "paint": "🎨"
};

export const CELEBRATION_MESSAGES = [
  "Dammmnn, well done lokki amar! I love you 💖",
  "Another one done! I am so proud of you my wife, I love you so so so much 🥰",
  "Look at you go! My strong, amazing wife crushing it today 💪❤️",
  "You did that!! Ekta ekta kore shob hobe, I believe in you always 🌸",
  "That's my girl! So proud of you every single day 😍💕",
  "Uff, you're incredible. Never forget that, lokki amar 🫶",
  "One more down! You make everything look so effortless, I love you ✨",
  "Proud husband moment 🥹 You're doing amazing sweetheart!",
  "Seri shundori amar! Another task done like a queen 👑💖",
  "I see you working hard! That's why I love you more every day 😘",
  "Mashallah! Look at my wife being absolutely unstoppable 🔥❤️",
  "Aww lokki, you make me the proudest husband in the world 🥺💕",
  "Ekta complete! Aro koto baki? Doesn't matter — I'll cheer every single one 💗",
  "You + productivity = the most beautiful thing I've ever seen 😭❤️",
  "That's it. That's the tweet. My wife is the best. I love you. 💌"
];

export const EMOJI_OPTIONS = ["✅", "💪", "📚", "😴", "🍽️", "📞", "🏃", "🧘", "💻", "💧", "💊", "🐾", "🛒", "🧹", "🎵", "🎨", "🙏", "📖", "✍️", "🏃‍♀️", "🧘‍♀️", "🚶‍♀️", "🍳", "☕", "🚿", "💄", "👗", "🏠", "💼", "🌱", "💖", "✨"];
